/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToast: typeof import('./components/AppToast.vue')['default']
    BotonTema: typeof import('./components/BotonTema.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    Detalles: typeof import('./components/Modals/Detalles.vue')['default']
    EquiposForm: typeof import('./components/Forms/EquiposForm.vue')['default']
    EstadoMemo: typeof import('./components/Modals/EstadoMemo.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ModalImagen: typeof import('./components/ModalImagen.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    PermisosForm: typeof import('./components/Forms/PermisosForm.vue')['default']
    ResponsablesForm: typeof import('./components/Forms/ResponsablesForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Ubicaciones: typeof import('./components/Forms/Ubicaciones.vue')['default']
  }
}
