/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToast: typeof import('./components/AppToast.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    EquiposForm: typeof import('./components/Forms/EquiposForm.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ResponsablesForm: typeof import('./components/Forms/ResponsablesForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
